service: serverless-boilerplate

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  timeout: 10 #Default Lambda timeout 
  memorySize: 512 #Default Lambda Memory Size
  versionFunctions: false # No functions versioning 
  #role: arn:aws:iam::#{AWS::AccountId}:role/existing-role
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**
      - .test/**
  
  environment: #Global Environment variables
      ${file(./configs/${self:provider.stage}.yml)}

  iamRoleStatements: # Permissions for all of your functions can be set here

  - Effect: Allow
    Action: # Gives permission to DynamoDB tables in a specific region
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:TransactWriteItems
    Resource: "arn:aws:dynamodb:*:*:*"

  - Effect: Allow
    Action: # Gives permission to Lambda execution
      - lambda:InvokeFunction
      - lambda:InvokeAsync
    Resource: "*"

  - Effect: Allow
    Action:
      - sqs:SendMessage
      - sqs:ReceiveMessage
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
    Resource:
      - Fn::GetAtt:
          - BooksQueueExample
          - Arn

  - Effect: Allow
    Action:
      - sqs:SendMessage
    Resource:
      - Fn::GetAtt:
          - BooksDeadLetterQueue
          - Arn

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  process: ${self:custom.prefix}-process
  config: ${self:custom.prefix}-config
  dynamo-books: ${self:custom.prefix}-BooksCatalog
  dynamo-books-event-state: ${self:custom.prefix}-BooksEventState
  dynamo-books-event-idempotency: ${self:custom.prefix}-BooksEventIdempotency
  sns-logs: ${self:custom.prefix}-trigger-logs
  sqs-logs: ${self:custom.prefix}-messages-logs
  sqs-books-dlq: ${self:custom.prefix}-messages-logs-dlq
  booksConsumer: ${file(./configs/books-consumer.js)}

  serverless-offline:
    host: '0.0.0.0'

  splitStacks:
    perFunction: true
    perType: true

  serverless-offline-sqs-esmq:
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    region: sa-east-1
    accessKeyId: root
    secretAccessKey: root

  dynamodb:
    stages:
      - local
      - test
      - dev

    start:
      host: "dynamo"
      port: 8000
      inMemory: false
      migrate: true
      noStart: true


plugins:
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline-sqs-esmq
  - serverless-offline

functions: ${file(serverless-dynamic.js)}

# Infrastrucure - Cloud Formation
resources:  # CloudFormation template syntax

  Resources:
    #DynamoDB Books Table
    BooksCatalog:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo-books}
        AttributeDefinitions:
          - AttributeName: hashkey
            AttributeType: S
        KeySchema:
          - AttributeName: hashkey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 1

    BooksEventState:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo-books-event-state}
        AttributeDefinitions:
          - AttributeName: hashKey
            AttributeType: S
        KeySchema:
          - AttributeName: hashKey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 1

    BooksEventIdempotency:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo-books-event-idempotency}
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 1

    BooksDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs-books-dlq}
        MessageRetentionPeriod: 1209600

    # SQS Queue to Update DynamoDB
    BooksQueueExample:
      Type: AWS::SQS::Queue
      DependsOn: BooksDeadLetterQueue
      Properties:
        QueueName: ${self:custom.sqs-logs}
        MessageRetentionPeriod: 1209600
        VisibilityTimeout: ${self:custom.booksConsumer.visibilityTimeoutSeconds}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - BooksDeadLetterQueue
              - Arn
          maxReceiveCount: ${self:custom.booksConsumer.maxReceiveCount}
