# Background Function
  books-consumer:
    handler: modules/books/functions/worker/handler.worker
    timeout: ${self:custom.booksConsumer.lambdaTimeoutSeconds}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - BooksQueueExample
              - Arn
          batchSize: ${self:custom.booksConsumer.batchSize}
          maximumBatchingWindow: ${self:custom.booksConsumer.maximumBatchingWindowSeconds}
          maximumConcurrency: ${self:custom.booksConsumer.maximumConcurrency}
          functionResponseType: ReportBatchItemFailures

  envs-temp:
    handler: modules/books/endpoints/read.envs
    timeout: 60
    events:
      - http:
          path: services/envs
          method: get
